### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by y-blip** [Sunfished/Pokemmon#1]
slight issue but on the latest version downloadable from TModLoader there is two Litten pokeballs and no scorbunny (when buying the starters from the professor npc.

is this a bug or a thing i can fix on my end

**Comment by y-blip** [comment]
forgot to add: when using the cheat sheet mod along side it the scorbunny pokeball is implemented just isn't appearing in the npc menu

**Comment by Sunfished** [comment]
Thank you for reaching out!

I just checked and it was an issue on my end, which has been corrected. This was due to me being careless and forgetting to set Scorbunny's Pokeball as a purchasable item, and instead duplicated Litten's. This fix will be applied in my next update, so thank you for catching it!
