### ISSUE TITLE
WorldGen crash

### ISSUE THREAD

**Issue by Chik3r** [Sunfished/Pokemmon#2]
(this crash was reported on the tModLoader discord)
When a world is created with your mod, the world creation screen gets stuck on `Generating structures... Minecart tracks`, here are the logs:
[client.log](https://github.com/Sunfished/Pokemmon/files/5770649/client.log)

**Comment by Sunfished** [comment]
Hey there!

Thanks for this report, I've managed to fix this issue in v0.3.3!

This problem was due to Water Chests taking in items meant for Regular Chests, which ended up causing an out-of-bounds error due to Regular Chests having less in the item pool than Water Chests. A dumb mistake on my part.
